"use client";
import "@rainbow-me/rainbowkit/styles.css";
import "bootstrap/dist/css/bootstrap.css";
import "../../styles/globals.scss";

import { gilroyFont } from "../../font/font";

import { ReactNode } from "react";
import { spaceGrotesk } from "../../utils/spaceGroteskFontFamily";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { WagmiProvider } from "wagmi";
import { arbitrum, arbitrumSepolia } from "wagmi/chains";
import {
  getDefaultConfig,
  RainbowKitProvider,
  createAuthenticationAdapter,
  RainbowKitAuthenticationProvider,
} from "@rainbow-me/rainbowkit";
import { SiweMessage } from "siwe";

// custom_components
import HeaderLk from "../../components/Headers/HeaderLk";
import Footer from "../../components/Footer/index";

// stores
import { setAuthenticated } from "../../stores/authenticated-store";
import { setJWT } from "../../stores/setJWT-store";
import { setInviteState } from "../../stores/setInviteState-store";
import { useRouter } from "next/navigation";

const config = getDefaultConfig({
  appName: "RainbowKit App",
  projectId: process.env.NEXT_PUBLIC_WALLET_CONNECT_ID as string,
  chains: [
    arbitrum,
    ...(process.env.NEXT_PUBLIC_ENABLE_TESTNETS === "true"
      ? [arbitrumSepolia]
      : []),
  ],
  ssr: true,
});

const client = new QueryClient({
  defaultOptions: {
    queries: {
      retryDelay: (attemptIndex) => Math.min(1000 * 2 ** attemptIndex, 30000),
    },
  },
});
const path =
  "https://devmy.dagama.world/assets/components/dga/conector_jwt.php";

const Layout = ({ children }: { children: ReactNode }) => {
  const authStatus = setAuthenticated((state) => state.authenticated);
  const setAuthStatus = setAuthenticated(
    (state) => state.setAuthenticatedStatus
  );
  const setJwtToken = setJWT((state) => state.setJwtToken);
  const setInvite = setInviteState((state) => state.setInviteState);

  const router = useRouter();

  const authenticationAdapter = createAuthenticationAdapter({
    getNonce: async () => {
      await new Promise((r) => setTimeout(r, 100));
      const nonce = "mockNonce"; // mock nonce
      return nonce;
    },

    createMessage: ({ nonce, address, chainId }) => {
      return new SiweMessage({
        domain: window.location.host,
        address,
        statement: "Sign in with Ethereum to the app.",
        uri: window.location.origin,
        version: "1",
        chainId,
        nonce,
      });
    },

    getMessageBody: ({ message }) => {
      return message.prepareMessage();
    },

    verify: async ({ message, signature }) => {
      const verifyRes = await fetch(path, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message, signature, request: "authLk" }),
      })
        .then((res) => {
          if (!res.ok) {
            throw new Error("Errror fetch data");
          }
          return res.json();
        })
        .then((data) => {
          setAuthStatus("authenticated");
          setJwtToken(data.object.jwt);
          setInvite(data.object.lk_state);
        })
        .catch((err) => console.log("Error status code: " + err.message));
      return true;
    },

    signOut: async () => {
      await fetch(`${path}?logout=true`);
      setAuthStatus("unauthenticated");
      router.push("/");
      setJwtToken("");
    },
  });

  return (
    <html lang="en" className={spaceGrotesk.className}>
      <head>
        <title>DaGama</title>
        <meta content="Generated by Primarch Dev" name="description" />
        {/* Обязательный (и достаточный) тег для браузеров */}
        <link
          type="image/x-icon"
          rel="shortcut icon"
          href="./icon/favicon.ico"
        />

        {/* Дополнительные иконки для десктопных браузеров */}
        <link
          type="image/png"
          sizes="16x16"
          rel="icon"
          href="./icon/favicon-16x16.png"
        />
        <link
          type="image/png"
          sizes="32x32"
          rel="icon"
          href="./icon/favicon-32x32.png"
        />
        <link
          type="image/png"
          sizes="96x96"
          rel="icon"
          href="./icon/favicon-96x96.png"
        />
        <link
          type="image/png"
          sizes="120x120"
          rel="icon"
          href="./icon/favicon-120x120.png"
        />

        {/* Иконки для Android */}
        <link
          type="image/png"
          sizes="72x72"
          rel="icon"
          href="./icon/android-icon-72x72.png"
        />
        <link
          type="image/png"
          sizes="96x96"
          rel="icon"
          href="./icon/android-icon-96x96.png"
        />
        <link
          type="image/png"
          sizes="144x144"
          rel="icon"
          href="./icon/android-icon-144x144.png"
        />
        <link
          type="image/png"
          sizes="192x192"
          rel="icon"
          href="./icon/android-icon-192x192.png"
        />
        <link
          type="image/png"
          sizes="512x512"
          rel="icon"
          href="./icon/android-icon-512x512.png"
        />

        {/* Иконки для iOS (Apple) */}
        <link
          sizes="57x57"
          rel="apple-touch-icon"
          href="./icon/apple-touch-icon-57x57.png"
        />
        <link
          sizes="60x60"
          rel="apple-touch-icon"
          href="./icon/apple-touch-icon-60x60.png"
        />
        <link
          sizes="72x72"
          rel="apple-touch-icon"
          href="./icon/apple-touch-icon-72x72.png"
        />
        <link
          sizes="76x76"
          rel="apple-touch-icon"
          href="./icon/apple-touch-icon-76x76.png"
        />
        <link
          sizes="114x114"
          rel="apple-touch-icon"
          href="./icon/apple-touch-icon-114x114.png"
        />
        <link
          sizes="120x120"
          rel="apple-touch-icon"
          href="./icon/apple-touch-icon-120x120.png"
        />
        <link
          sizes="144x144"
          rel="apple-touch-icon"
          href="./icon/apple-touch-icon-144x144.png"
        />
        <link
          sizes="152x152"
          rel="apple-touch-icon"
          href="./icon/apple-touch-icon-152x152.png"
        />
        <link
          sizes="180x180"
          rel="apple-touch-icon"
          href="./icon/apple-touch-icon-180x180.png"
        />

        {/* Иконки и цвета для плиток Windows */}
        <meta name="msapplication-TileColor" content="#2b5797" />
        <meta
          name="msapplication-TileImage"
          content="./icon/mstile-144x144.png"
        />
        <meta
          name="msapplication-square70x70logo"
          content="./icon/mstile-70x70.png"
        />
        <meta
          name="msapplication-square150x150logo"
          content="./icon/mstile-150x150.png"
        />
        <meta
          name="msapplication-wide310x150logo"
          content="./icon/mstile-310x310.png"
        />
        <meta
          name="msapplication-square310x310logo"
          content="./icon/mstile-310x150.png"
        />
        <meta name="application-name" content="DaGama" />
      </head>
      <body className={gilroyFont.className}>
        <WagmiProvider config={config}>
          <QueryClientProvider client={client}>
            <RainbowKitAuthenticationProvider
              adapter={authenticationAdapter}
              status={authStatus}
            >
              <RainbowKitProvider initialChain={arbitrum}>
                <div className="appWrapper">
                  <HeaderLk />
                  <div className="appContent">{children}</div>
                  <Footer />
                </div>
              </RainbowKitProvider>
            </RainbowKitAuthenticationProvider>
          </QueryClientProvider>
        </WagmiProvider>
      </body>
    </html>
  );
};

export default Layout;
